kumuluzee:
  name: webflix-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/WebflixDS
      connection-url: jdbc:postgresql://localhost:5432/webflix
      username: postgres
      password: postgres
      max-pool-size: 20
#  config:
#    start-retry-delay-ms: 500
#    max-retry-delay-ms: 900000
#    etcd:
#      hosts: http://localhost:2379 #,http://192.168.99.101:2379,http://192.168.99.102:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/WebflixDS
#      etcd-health-check:
#        type: liveness
#        connection-url: http://localhost:2379/health
  metrics:
    web-instrumentation:
      - name: videos-endpoint
        url-pattern: /v1/videos/*
        status-codes: "200, 500"
    servlet:
      enabled: true
      mapping: /metrics
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="webflix">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="b8984ee4-2843-4b14-8436-aa7825515a40-ls.logit.io"
                          port="10033" protocol="udp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info" />
                              <AppenderRef ref="logstash" level="trace" />
                          </Root>
                      </Loggers>
                  </Configuration>'
  security:
    keycloak:
      json: '{
               "realm": "webflix-realm",
               "bearer-only": true,
               "auth-server-url": "http://localhost:8082/auth/",
               "ssl-required": "external",
               "resource": "webflix-api",
               "confidential-port": 0
             }'
rest-config:
  maintenance-mode: false
  broken: false
