kumuluzee:
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379 #,http://192.168.99.101:2379,http://192.168.99.102:2379
  name: webflix-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/VideoMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/video-metadata # jdbc:postgresql://34.89.177.84:5432/webflix-database
      username: postgres
      password: postgres # FPChtPMCl5K1MowA
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/VideoMetadataDS
  #      etcd-health-check:
  #        type: liveness
  #        connection-url: http://localhost:2379/health
rest-config:
  maintenance-mode: false
